# Generated by Django 2.2.4 on 2020-12-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showsApp', '0002_auto_20201214_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='desc',
            field=models.TextField(default='nth'),
        ),
        migrations.AlterField(
            model_name='show',
            name='network',
            field=models.CharField(default='network', max_length=255),
        ),
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(default='title', max_length=255),
        ),
    ]
